### ISSUE TITLE
Basemaps with a spatial reference other than 102100 cause Shortlist to hang.

### ISSUE THREAD

**Issue by AshleyDesktop** [Esri/shortlist-storytelling-template-js#32]
Web maps that contain basemaps with a Spatial Reference that differs from the Esri default basemaps (Web Mercator Aux Sphere WKID 102100) may cause Shortlist to hang.

Tested with WKID 27700 and 26912.

**Comment by mullearn** [comment]
Having the same problem with the Czech National Coordinate system EPSG 5514, using a topographic layer as a basemap in this CS and a point shapefile in this system causes this app to hang... Unlike the other storytelling basic template, which works... Any ideas?

**Comment by cooney** [comment]
Installed with version 1.4.
