### ISSUE TITLE
Short list changes website URL to lower case

### ISSUE THREAD

**Issue by mac44** [Esri/shortlist-storytelling-template-js#41]
The AGO web map shows the Google short URL in the Website field as it should be (case sensitive with upper and lower case).  The short list template, however, consumes the web map and somehow changes the URLs in the website field, which is used for the Directions link, to all lower case thereby breaking the link.  Does anyone know of a fix for this issue?

**Comment by RupertEssinger** [comment]
This is in the current Shortlist download since Nov 2014
