### ISSUE TITLE
Can't open webmap that is in Organizational portal.

### ISSUE THREAD

**Issue by cblandy** [Esri/shortlist-storytelling-template-js#47]
I have download the template onto our web servers and tried to use a web map that I created on our own Organizational portal. I get the following error. Map Creation Failed:  Item does not exist or is inaccessible.

The webmap id is: b1a2a6cf4c2547c79819c954b2c48c6c

It has been shared to the public.

Does anybody have any thoughts as to why this is happening?

Cameron

**Comment by cooney** [comment]
Installed with version 1.4.2.

**Comment by cooney** [comment]
@cblandy in the index.html, please include the appropriate URL for your portal to the DEFAULT_SHARING_URL variable.

// Edit to use Portal for ArcGIS
var DEFAULT_SHARING_URL = "";
//"http://www.example.com/arcgis/sharing/content/items";
