### ISSUE TITLE
SUPPORTING_LAYERS_THAT_ARE_CLICKABLE not working for ArcGIS for Server Map  Service

### ISSUE THREAD

**Issue by cblandy** [Esri/shortlist-storytelling-template-js#53]
I have a polygon layer within a ArcGIS for Server Map Service that I would like to be used as a Supporting Layer that is clickable. I have added it to the web map and configured it using the SUPPORTING_LAYERS_THAT_ARE_CLICKABLE variable in index.html. The layer contains both a name and Description field. Any clues why this is not working?
Regards,
Cameron

**Comment by cooney** [comment]
Cameron,

Please use the Story Maps GeoNet forums for these types of questions.
<https://geonet.esri.com/community/gis/web-gis/storymaps/content>
