### ISSUE TITLE
Why call function init() two times in file "app/js/main.js"?

### ISSUE THREAD

**Issue by ly2015** [Esri/shortlist-storytelling-template-js#55]
What is written in file "app/js/main.js"  is as follows:

dojo.addOnLoad(function() {_dojoReady = true;init();});
jQuery(document).ready(function() {_jqueryReady = true;init();});

------
Could I call function init() only one time? and How?

**Comment by glazou** [comment]
Yes but you shouldn't need this.
This allow the app to handle well case where jquery may be loaded in a different order. 

The `init` function will be called twice but the first thing that function does is to check that both jQuery and Dojo are loaded so the code should only be executed once, see https://github.com/Esri/shortlist-storytelling-template-js/blob/master/app/js/main.js#L96
