### ISSUE TITLE
Images wont appear

### ISSUE THREAD

**Issue by dhj2337** [Esri/shortlist-storytelling-template-js#61]
My ArcGIS online web map works with images but It show on the storytelling template. I have edited the size of the images as well. Can someone help me with this? I am new to using this. 
 Here is the link for my app : http://gis6370.com/jayasuriya/final/index.html

**Comment by RupertEssinger** [comment]
Your image URLs are in a field called PIC that the Shortlist doesn't recognize. Change that field name to PIC_URL in your data and it will work.

**Comment by dhj2337** [comment]
THANK YOU SO MUCH!!!! It worked perfectly!

**Comment by RupertEssinger** [comment]
Good to know thanks!
