### ISSUE TITLE
Enable geocoder

### ISSUE THREAD

**Issue by triesco** [Esri/shortlist-storytelling-template-js#66]
Cant enable geocoder. I enabled it on the config.js file but still doesn't show geocoder. Any ideas?? Thanks!

**Comment by cooney** [comment]
@triesco this functionality is not hooked up yet in version 2.  We cleaned up the config file in the most previous release to remove that parameter.  Sorry for the inconvenience.

**Comment by triesco** [comment]
Any other way to enable it?

**Comment by cooney** [comment]
There is not, but it is an enhancement we will look to include in a future release
