### ISSUE TITLE
How do I add search and layerlist widgets in StoryMap shortlist?

### ISSUE THREAD

**Issue by JudyZhou** [Esri/shortlist-storytelling-template-js#67]
In the downloaded version, How do I add search and layerlist widgets in StoryMap shortlist? Please help!

**Comment by cooney** [comment]
Have a look at this post on our forums on GeoNet <https://geonet.esri.com/thread/188951-search-multiple-sources>.  That should get you started on adding the search widget, and the layerlist widget would be implemented in a similar fashion.
