### ISSUE TITLE
Change the design of the popups so that the title of the place can't run into the close control that is at the right edge of the title bar.

### ISSUE THREAD

**Issue by leebock** [Esri/shortlist-storytelling-template-js#9]
Could we handle the issue where long popup titles can run into the Close control. This happens a lot if the user's web browser is window is fairly narrow, such as on the iPad, and looks really bad. 

 
![one](https://f.cloud.github.com/assets/285913/473718/c640c3bc-b755-11e2-95b5-60b4db0e979d.png)

Can we change the styling of the popup to avoid this overlap by putting the title of the place into the popup body instead of in the title bar? That is how the standard popups in ArcGIS web maps work: they don't put the name of the place in the title bar.  The extra vertical height this needs isn't a big deal because we aren't short of vertical space in the display. Here is how it would look:

 
![two](https://f.cloud.github.com/assets/285913/473719/c9587eaa-b755-11e2-9dd4-f46ae3a54f22.png)

The design above looks better when the title is fairly long, because it avoids the wrap around in the title bar that makes the title bar taller. So this enhancement eliminates that issue too.

 
![three](https://f.cloud.github.com/assets/285913/473720/cba7bd6a-b755-11e2-818b-0cb170eaf2d9.png)

**Comment by cooney** [comment]
Installed with version 1.4.
